name: SLO
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:
jobs:
  native:
    if: github.event.pull_request.head.repo.full_name == 'ydb-platform/ydb-go-sdk'
    uses: ydb-platform/slo-tests/.github/workflows/slo.yml@main
    secrets: inherit
    with:
      language_id: go-native
      language: go/v3/native
      workload_path: tests/slo
      workload_build_options: -f Dockerfile --build-arg SRC_PATH=native
      workload_build_context: ../..
#  database_sql:
#    needs: native
#    if: github.event.pull_request.head.repo.full_name == 'ydb-platform/ydb-go-sdk'
#    uses: ydb-platform/slo-tests/.github/workflows/slo.yml@main
#    secrets: inherit
#    with:
#      language_id: go-database-sql
#      language: go/v3/database/sql
#      workload_path: tests/slo
#      workload_build_options: -f Dockerfile --build-arg SRC_PATH=database/sql
#      workload_build_context: ../..
